# Generated by Django 2.0.5 on 2018-07-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Phone')),
            ],
        ),
    ]
